### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by jaimergp** [vlakarados/gitstatus#1]
Hi, I am using ST2 and couldn't get it to work.

I installed it with Package Control and manually, and both methos worked apparently ok (the gitstatus folder was created and populated with files), but none of the options were available in ST (even after a theoretically unneeded restart).
The status bar remained intact, and Ctrl+shift+p palette didn't offer any related commands.

Some tech info:
ST2.0.0 build 2221, under Ubuntu 12.04.

Thanks!

**Comment by vlakarados** [comment]
The thing is I had no chance of testing it under ST2. Can you please uninstall it completely, then having console (`ctrl+``) opened install it. See if it throws any errors and post them here please, I will do my best to fix this asap after getting my hands on ST2.

**Comment by jaimergp** [comment]
Oh, right, the console. Now I see why it wasn't working:

```
Error loading commands: Error trying to parse file: Trailing comma before closing bracket in ~/.config/sublime-text-2/Packages/GitStatus/Default.sublime-commands:10:1
```

I removed that trailing comma, and now it loads OK, but a new error arises when trying to execute any command:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 339, in run_
  File "./GitStatus.py", line 132, in run
  File "./GitStatus.py", line 52, in all
  File "./GitStatus.py", line 59, in check
AttributeError: 'module' object has no attribute 'check_output'
```

, which is really weird, because it has to do with subprocess.check_output. I've checked and std python (2.7.3) runs it fine. I got no idea!

Thanks for your time!
