### ISSUE TITLE
in SublimeText 3, opening file in dir used the wrong filename / path

### ISSUE THREAD

**Issue by wiiiimm** [vlakarados/gitstatus#4]
for a modified file in 'folder/folder/filename' it will try to open the filename 'folderfolderfilename' instead. i guess the '/' it is missing the '/'

**Comment by vlakarados** [comment]
Fixed in commit https://github.com/vlakarados/gitstatus/commit/5a2f28b2d9aeb357de0f121fe7fef5bdec0ca862

Thank's for reporting!
